version: '3'
services:
  memcached:
    image: memcached:1.6-alpine
    ports:
      - "11211:11211"
    restart: always

  pgsql:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: root
      POSTGRES_DB: "forge"
  redis:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
    restart: always
